/**
 * scratch/runtimeVerifyR03Approve.ts
 *
 * Controlled runtime verification for R03 — Approve Path.
 * Proves:
 *   1. Initial workspace disk file: "ORIGINAL A"
 *   2. Developer generates proposal -> state receives proposal
 *   3. BEFORE APPROVAL: Disk file remains "ORIGINAL A" (0 bytes modified)
 *   4. ApprovalRequest generated with file count, relative path, action, summary
 *   5. Human APPROVE resolved
 *   6. AFTER APPROVAL: Disk file becomes "MODIFIED B"
 *   7. Developer generation call count: 1 (0 extra LLM calls on resume)
 */

import os from "os";
import path from "path";
import { promises as fs } from "fs";
import { createDeveloperNode } from "../graph/nodes/developerNode.js";
import { buildApprovalWorkflow, executeApprovalWorkflow, resolveApprovalAndResume } from "../graph/approvalWorkflow.js";
import { DeveloperAgent } from "../agents/developer/developer.js";
import type { DeveloperModel } from "../agents/developer/developer.js";
import type { AegisState, AegisStateUpdate } from "../graph/state.js";

let devGenerationCount = 0;

const mockDevModel: DeveloperModel = {
  async generateStructured<T>(_sys: string, _user: string, _schema: unknown): Promise<T> {
    devGenerationCount++;
    return {
      task: "Update index.ts file",
      summary: "Updated index.ts with feature implementation",
      fileChanges: [
        {
          path: "src/index.ts",
          action: "modify",
          summary: "Implemented core feature function B",
          content: "// MODIFIED B\nexport function featureB() { return 'B'; }",
        },
      ],
      commandsExecuted: [],
      status: "completed",
    } as unknown as T;
  },
};

const mockPlanner = async (_s: AegisState): Promise<AegisStateUpdate> => ({
  status: "planning",
  plan: [{ id: "step-1", description: "Implement feature B", status: "completed" }],
});

const mockResearcher = async (_s: AegisState): Promise<AegisStateUpdate> => ({
  status: "researching",
  research: "Research notes for feature B",
});

const mockArchitect = async (_s: AegisState): Promise<AegisStateUpdate> => ({
  status: "architecting",
  architecture: "Architectural spec for feature B",
});

const mockTester = async (_s: AegisState): Promise<AegisStateUpdate> => ({
  status: "testing",
  testResults: { passed: true, totalTests: 1, passedTests: 1, failedTests: 0, output: "Tests passed" },
});

const mockReviewer = async (_s: AegisState): Promise<AegisStateUpdate> => ({
  status: "reviewing",
  reviewResults: { approved: true, comments: ["LGTM"] },
});

async function run(): Promise<void> {
  console.log("=== R03 RUNTIME VERIFICATION — APPROVE PATH ===\n");

  const testWs = path.join(os.tmpdir(), `aegis-r03-approve-${Date.now()}`);
  await fs.mkdir(path.join(testWs, "src"), { recursive: true });
  const targetFile = path.join(testWs, "src", "index.ts");
  await fs.writeFile(targetFile, "// ORIGINAL A\nexport function featureA() { return 'A'; }", "utf-8");

  const initialDiskContent = await fs.readFile(targetFile, "utf-8");
  console.log("1. Disk before proposal generation:");
  console.log(`   File: src/index.ts`);
  console.log(`   Content:\n${initialDiskContent.trim()}`);

  const devAgent = new DeveloperAgent(mockDevModel);
  const devNode = createDeveloperNode(devAgent);
  const workflow = buildApprovalWorkflow({
    planner: mockPlanner,
    researcher: mockResearcher,
    architect: mockArchitect,
    developer: devNode,
    tester: mockTester,
    reviewer: mockReviewer,
  });

  const runId = `r03_verify_approve_${Date.now()}`;

  // Step 1: Initial run up to approval gate pause
  console.log("\n2. Invoking Aegis Workflow (Planner -> Researcher -> Architect -> Developer Prepare -> Approval Gate)...");
  const pausedState = await executeApprovalWorkflow(runId, { task: "Update index.ts", workspace: testWs }, workflow);

  const diskAfterProposal = await fs.readFile(targetFile, "utf-8");
  console.log("\n3. Disk state AFTER proposal generation, BEFORE approval:");
  console.log(`   File: src/index.ts`);
  console.log(`   Content:\n${diskAfterProposal.trim()}`);
  console.log(`   Match Initial Disk: ${diskAfterProposal === initialDiskContent ? "YES (100% UNCHANGED)" : "NO (MUTATED!)"}`);

  console.log("\n4. ApprovalRequest generated by Approval Gate:");
  const req = pausedState.pendingApproval;
  if (req) {
    console.log(`   Request ID: ${req.id}`);
    console.log(`   Title: ${req.title}`);
    console.log(`   Target: ${req.target}`);
    console.log(`   Description:\n${req.description}`);
  } else {
    console.error("   ERROR: No ApprovalRequest found!");
  }

  console.log(`\n5. Developer generation call count prior to approval: ${devGenerationCount}`);

  // Step 2: Human resolves approval
  console.log("\n6. Resolving approval with decision: APPROVE...");
  const resumedState = await resolveApprovalAndResume(runId, req!.id, "approve", "Approved by lead", workflow);

  const diskAfterApproval = await fs.readFile(targetFile, "utf-8");
  console.log("\n7. Disk state AFTER approval resolution:");
  console.log(`   File: src/index.ts`);
  console.log(`   Content:\n${diskAfterApproval.trim()}`);

  console.log(`\n8. Developer generation call count after approval: ${devGenerationCount}`);
  console.log(`   Zero extra LLM calls on resume: ${devGenerationCount === 1 ? "YES" : "NO"}`);
  console.log(`   Final workflow status: ${resumedState.status}`);

  // Cleanup
  try { await fs.rm(testWs, { recursive: true, force: true }); } catch {}

  console.log("\n=== APPROVE PATH RUNTIME VERIFICATION COMPLETE ===");
}

run().catch((err) => {
  console.error("Verification failed:", err);
  process.exit(1);
});
